import CampusCostMethods

#CampusCostMethods.newBuilding("Douglass_Houghton_Hall", "DHH")

#CampusCostMethods.newVM("Douglass_Houghton_Hall", "123")

CampusCostMethods.newProduct("Classic Lays", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Nacho Cheese Doritos", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Cool Ranch Doritos", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Classic Cheetos", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Cheetos Fries", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Harvest Cheddar Sun Chips", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Tostitos Crispy Rounds", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("BBQ Deep River Chips", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Sweet Onion Deep River Chips", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Salt & Cracked Pepper Deep River Chips", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Cheez-Its", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Mother's Circus Animal Cookies", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Grandma's Vanilla Creme Cookies", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Oreo Minis", 3.25, "VMDHH1232")
CampusCostMethods.newProduct("Jack Links Beef Tender Cuts", 3.75, "VMDHH1232")
CampusCostMethods.newProduct("Sour Patch Kids", 4.00, "VMDHH1232")
CampusCostMethods.newProduct("Haribo Goldbears", 4.00, "VMDHH1232")
CampusCostMethods.newProduct("Trolli Sour Brite Crawlers", 4.00, "VMDHH1232")
CampusCostMethods.newProduct("Nerds Gummy Clusters", 4.00, "VMDHH1232")
CampusCostMethods.newProduct("Gushers", 4.00, "VMDHH1232")
CampusCostMethods.newProduct("Snickers", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Peanut M&Ms", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Sweet Tarts", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Twix", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Reese's Peanut Butter Cups", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Reese's Sticks", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Blueberry Nature's Bakery Fig Bar", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Nature Valley Granola Bar", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Kars Trail Mix", 2.50, "VMDHH1232")
CampusCostMethods.newProduct("Jack Links Beef Stick", 3.00, "VMDHH1232")
CampusCostMethods.newProduct("Famous Amos Cookies", 1.75, "VMDHH1232")
CampusCostMethods.newProduct("Black Forest Juicy Burst", 1.75, "VMDHH1232")
CampusCostMethods.newProduct("Nutty Buddy", 1.75, "VMDHH1232")
CampusCostMethods.newProduct("Freshly's Donut Sticks", 2.25, "VMDHH1232")
CampusCostMethods.newProduct("Cherry Pop-Tarts", 2.25, "VMDHH1232")